const main = async () => {
  try {
    console.log('Hello World');
  } catch (error) {
    console.error('[error]', error);
  }
};

main();
